[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "/app/start.sh"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[[services]]
  name = "web"
  internal_port = 8000
  protocol = "http"
  auto_deploy = true

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800