[build]
  builder = "nixpacks"

[deploy]
  startCommand = "./start.sh"
  healthcheckPath = "/health"
  healthcheckTimeout = 30
  restartPolicyType = "on-failure"
  restartPolicyMaxRetries = 3

[build.environment]
  NODE_VERSION = "18.x"
  PYTHON_VERSION = "3.11"

[build.install]
  - pip install -r requirements.txt

[build.build]
  - pip install -r requirements.txt
  - python -m pip install --upgrade pip

[build.start]
  - ./start.sh

[[services]]
  name = "web"
  internal_port = 8000
  protocol = "http"
  auto_deploy = true

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800