[build]
builder = "nixpacks"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 30

[build.environment]
NODE_VERSION = "18.x"
PYTHON_VERSION = "3.11"

[[services]]
name = "web"
port = 8000

[healthcheck]
timeout = 30
interval = 30
retries = 3