"""update_product_relationship_cascade

Revision ID: 070e1c583426
Revises: 86cb1ffafd78
Create Date: 2025-08-28 10:17:17.460901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070e1c583426'
down_revision: Union[str, None] = '86cb1ffafd78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
