"""add_salary_to_users

Revision ID: 7d4708e70d76
Revises: 002c68f0fdd9
Create Date: 2025-08-26 09:38:52.550366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4708e70d76'
down_revision: Union[str, None] = '002c68f0fdd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_barcode', table_name='products')
    op.drop_column('products', 'max_stock')
    op.drop_column('products', 'wholesale_price')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'is_service')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_index('ix_users_refresh_token', table_name='users')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True, comment='Token de atualização JWT'))
    op.create_index('ix_users_refresh_token', 'users', ['refresh_token'], unique=False)
    op.alter_column('users', 'salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('products', sa.Column('is_service', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('barcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('wholesale_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('max_stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    # ### end Alembic commands ###
