"""remove_is_service_from_products

Revision ID: 86cb1ffafd78
Revises: d8ba6614d330
Create Date: 2025-08-28 09:59:32.195922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cb1ffafd78'
down_revision: Union[str, None] = 'd8ba6614d330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_service')
    op.drop_column('sale_items', 'discount')
    op.drop_column('sales', 'amount_received')
    op.drop_column('sales', 'change')
    op.alter_column('users', 'salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.add_column('sales', sa.Column('change', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('amount_received', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('sale_items', sa.Column('discount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('is_service', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
