"""add_venda_por_peso_to_products

Revision ID: f3bdf51afafe
Revises: c162b555c015
Create Date: 2025-08-18 07:05:11.744830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bdf51afafe'
down_revision: Union[str, None] = 'c162b555c015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('venda_por_peso', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'venda_por_peso')
    # ### end Alembic commands ###
