"""add_weight_fields_to_sale_items

Revision ID: f8eefa29ef34
Revises: add_permissions
Create Date: 2025-09-02 19:14:53.197247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8eefa29ef34'
down_revision: Union[str, None] = 'add_permissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_categories_last_updated'), table_name='categories')
    op.drop_column('categories', 'synced')
    op.drop_column('categories', 'last_updated')
    op.drop_index(op.f('idx_customers_last_updated'), table_name='customers')
    op.drop_column('customers', 'synced')
    op.drop_column('customers', 'last_updated')
    op.alter_column('employees', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employees', 'can_sell',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employees', 'can_manage_inventory',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employees', 'can_manage_expenses',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_employees_last_updated'), table_name='employees')
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'last_updated')
    op.drop_column('employees', 'synced')
    op.drop_index(op.f('idx_products_last_updated'), table_name='products')
    op.drop_column('products', 'synced')
    op.drop_column('products', 'last_updated')
    op.add_column('sale_items', sa.Column('is_weight_sale', sa.Boolean(), nullable=True))
    op.add_column('sale_items', sa.Column('weight_in_kg', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('sale_items', sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('sale_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.drop_index(op.f('idx_sale_items_last_updated'), table_name='sale_items')
    op.drop_column('sale_items', 'synced')
    op.drop_column('sale_items', 'last_updated')
    op.drop_index(op.f('idx_sales_last_updated'), table_name='sales')
    op.drop_column('sales', 'synced')
    op.drop_column('sales', 'last_updated')
    op.drop_index(op.f('idx_users_last_updated'), table_name='users')
    op.drop_column('users', 'synced')
    op.drop_column('users', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_users_last_updated'), 'users', ['last_updated'], unique=False)
    op.add_column('sales', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_sales_last_updated'), 'sales', ['last_updated'], unique=False)
    op.add_column('sale_items', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('sale_items', sa.Column('synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_sale_items_last_updated'), 'sale_items', ['last_updated'], unique=False)
    op.alter_column('sale_items', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('sale_items', 'custom_price')
    op.drop_column('sale_items', 'weight_in_kg')
    op.drop_column('sale_items', 'is_weight_sale')
    op.add_column('products', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_products_last_updated'), 'products', ['last_updated'], unique=False)
    op.add_column('employees', sa.Column('synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('role', postgresql.ENUM('admin', 'manager', 'cashier', 'viewer', name='employeerole'), server_default=sa.text("'cashier'::employeerole"), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_employees_last_updated'), 'employees', ['last_updated'], unique=False)
    op.alter_column('employees', 'can_manage_expenses',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('employees', 'can_manage_inventory',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('employees', 'can_sell',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('employees', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.add_column('customers', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_customers_last_updated'), 'customers', ['last_updated'], unique=False)
    op.add_column('categories', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_categories_last_updated'), 'categories', ['last_updated'], unique=False)
    # ### end Alembic commands ###
